<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="5" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="swatikagalkarprojects.Tests.ErrorValidationsTest">
        <methods>
          <include name="loginErrorValidation"/>
          <include name="launchApplication"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- swatikagalkarprojects.Tests.ErrorValidationsTest -->
      <class name="swatikagalkarprojects.Tests.SubmitOrderTest">
        <methods>
          <include name="orderHistoryTest"/>
          <include name="launchApplication"/>
          <include name="submitOrder" invocation-numbers="0"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- swatikagalkarprojects.Tests.SubmitOrderTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
